name = "mirror-search"
version = "2.1.0"
type = "html"
production_host = "coffee-cockroach-rachelle-6byahvr4.bls.dev"
environment = "production"

[deployment]
permission = "public"
nodes = 1
permissions = [
  "https://api.duckduckgo.com/",
  "https://api.brightdata.com/",
  "https://mirror-search-proxy.onrender.com/",
  "https://www.google.com/",
  "https://www.bing.com/",
  "https://search.yahoo.com/",
  "https://fonts.googleapis.com/",
  "https://fonts.gstatic.com/"
]

[build]
dir = "build"
entry = "index.ts"
command = "npm run build"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeifppmqjrwb5wk5iudluwrcbdps5fwjpwd5jqwxsqwejyuhhjka7ti"
created = "2025-06-01T05:28:13.027Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "f0c326a0f0918463c7b16c9cde45e41db77314359a28c73801094f82278880e5"

[permissions]
fs = [ "read", "write" ]

[features]
wasm = true
llm = true
privacy = true
fetch = true

[metadata]
title = "Mirror Search - Privacy-First AI Search Engine"
description = "Advanced search engine with WASM LLM query anonymization"
author = "Mirror Search Team"
license = "MIT"
