name = "mirror-search"
version = "2.1.0"
type = "html"
production_host = "coffee-cockroach-rachelle-6byahvr4.bls.dev"
environment = "production"

[deployment]
permission = "public"
nodes = 1
permissions = [
  "https://api.duckduckgo.com/",
  "https://www.google.com/",
  "https://www.bing.com/",
  "https://search.yahoo.com/",
  "https://fonts.googleapis.com/",
  "https://fonts.gstatic.com/"
]

[build]
dir = "build"
entry = "index.ts"
command = "npm run build"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeicyaduwyun4xbhhr5qn4djm4wmz4demm4rnqc2vs3udguqb5ulyli"
created = "2025-05-25T19:47:33.744Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "a4e27dfba3c489efba6c8b648a34fc976d891b70b94a68b900ccff4b0522ecf2"

[permissions]
fs = [ "read", "write" ]
network = [
  "api.duckduckgo.com",
  "fonts.googleapis.com",
  "fonts.gstatic.com"
]

[features]
wasm = true
llm = true
privacy = true

[metadata]
title = "Mirror Search - Privacy-First AI Search Engine"
description = "Advanced search engine with WASM LLM query anonymization"
author = "Mirror Search Team"
license = "MIT"
