name = "mirror-search"
version = "1.0.0"
type = "html"
production_host = "coffee-cockroach-rachelle-6byahvr4.bls.dev"
environment = "production"

[deployment]
permission = "public"
nodes = 1
permissions = [
  "https://api.duckduckgo.com/",
  "https://reqres.in/"
]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeicuaztkbnjk24ppgfmi3vmxdkc6tywjlhtdrncavtvjwtmm7q4lfy"
created = "2025-05-23T15:54:58.372Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "f9f895afb7e5e3f340e4362cb4f78c0d54807965af86dbc7c2e23e47fa294507"
