name = "mirror-search"
version = "2.1.0"
type = "html"
production_host = "coffee-cockroach-rachelle-6byahvr4.bls.dev"
environment = "production"

[deployment]
permission = "public"
nodes = 1
permissions = [
  "https://api.duckduckgo.com/",
  "https://api.brightdata.com/",
  "https://mirror-search-proxy.onrender.com/",
  "https://www.google.com/",
  "https://www.bing.com/",
  "https://search.yahoo.com/",
  "https://fonts.googleapis.com/",
  "https://fonts.gstatic.com/"
]

[build]
dir = "build"
entry = "index.ts"
command = "npm run build"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeibyuteiptt4kiz5fo4bjlh3pjxxaq66yfmommjt67emss5ichp5dq"
created = "2025-05-31T19:47:24.981Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "13fe1eed769bfaf4b54c0ae233a9a70fabf2d5b9eaa95fcd7a21e817ef43c6ce"

[permissions]
fs = [ "read", "write" ]

[features]
wasm = true
llm = true
privacy = true
fetch = true

[metadata]
title = "Mirror Search - Privacy-First AI Search Engine"
description = "Advanced search engine with WASM LLM query anonymization"
author = "Mirror Search Team"
license = "MIT"
